version: '3'

services:
  elasticsearch:
    build:
      context: ./els
    container_name: tkow-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  postgres:
    build:
      context: ./postgres
    container_name: tkow-postgres
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_MONITORING_ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "false"
    ports:
     - 80:5601
    networks:
      - kibana_net
    mem_limit: 2g
    memswap_limit: 2g
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  esdata:
    driver: local
networks:
  esnet:

