version: '3'

services:
  elasticsearch:
    build:
      context: ./els
    container_name: tkow-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - kibana_net
  postgres:
    build:
      context: ./postgres
    container_name: tkow-postgres
    networks:
      - kibana_net
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    container_name: kibana
    environment:
      - mem_limit=2g
      - memswap_limit=2g
    ports:
     - 80:5601
    networks:
      - kibana_net
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.1
    container_name: kibana
    environment:
      - memswap_limit= 2g
    depends_on:
      - elasticsearch
    networks:
      - kibana_net
    ports:
      - '5044:5044'
      - '43448:43448/udp'
      - '9600:9600'

volumes:
  esdata:
    driver: local
networks:
  kibana_net:

